#!/bin/bash

# Global Variables
case_path=""
case_name=""
bin_path=""

debug_mode=false

# ============= Internal Functions ==============
function usage()
{
    echo "Usage:"
    echo " - skull-ft -p case_path [-n case_name] [-D]"
}

function runOneCase()
{
    # 1. Enter case running folder
    local config="skull_ft_case.yml"
    local topdir=`pwd`
    local caseName=$1
    local casedir="$topdir/cases/$caseName"
    local rundir=$topdir/run/$caseName
    local caseconf="$casedir/$config"
    local logfile="$rundir/output.txt"

    if [ "$topdir" = "/" ]; then
        echo "Error: case topdir is '/', move it to other folder"
        return 1
    fi

    if [ ! -f "$caseconf" ]; then
        echo "Error: not found $caseconf, skip this case"
        return 0
    fi

    if [ -d "$rundir" ]; then
        rm -rf "$rundir"
    fi
    mkdir -p "$rundir"

    # 2. Run Case
    echo -n "[$caseName] running ... "
    (
        cd "$rundir"
        $bin_path/skull-case-executor.py -t $topdir -n $caseName -c $caseconf || exit 1
    ) > $logfile 2>&1;

    if [ $? -eq 0 ]; then
        echo "OK"
    else
        echo "Failed! Check the log file $logfile for the details"

        if $debug_mode; then
            echo ">>>>>>>>>>>>>>>>>> Diagnosis for $caseName >>>>>>>>>>>>>>>>>>"
            cat $logfile
            echo ">>>>>>>>>>>>>>>>>> Diagnosis for $caseName End >>>>>>>>>>>>>>>>>>"
        fi
    fi
}

function runAllCases()
{
    ls -1 "cases" | while read caseName; do
        if [ -z "$caseName" ]; then
            echo "'case name' is empty, skip it"
            continue
        fi

        if [ ! -d "cases/$caseName" ]; then
            echo "case ["$caseName"] is not a folder, skip it"
            continue
        fi

        runOneCase "$caseName"
    done
}

function runCases()
{
    # 1. Enter case path
    cd "$case_path"

    # 2. Run all cases or one case
    if [ -z "$case_name" ]; then
        runAllCases
    else
        runOneCase "$case_name"
    fi
}

# ============= main ==============
# 1. Check args
if [ $# = 0 ]; then
    echo "Missing 'case path' arg"
    usage
    exit 1
fi

while true; do
    case "$1" in
        (-p)
            case_path=$2
            shift 2
            ;;
        (-n)
            case_name=$2
            shift 2
            ;;
        (-D)
            debug_mode=true
            shift
            ;;
        (*)
            break
            ;;
    esac
done

# Export this var to subshells
export debug_mode
echo "Debug mode: $debug_mode"

if [ ! -z "$SKULLFT_BINPATH" ]; then
    bin_path="$SKULLFT_BINPATH"
else
    bin_path=`dirname $0`
    bin_path=`readlink -e $bin_path` # Get absolute path of the 'bin_path'
fi

# 2. Basic arg validation
if [ -z "$case_path" ]; then
    echo "Error: case path is empty, cannot run case"
    exit 1
fi

if [ ! -d "$case_path" ]; then
    echo "Error: case path ["$case_path"] is not a folder, cannot run case"
    exit 1
fi

if [ "$case_path" = "/" ]; then
    echo "Error: case_path($case_path) is '/', cannot run the cases. Move it to other folder"
    exit 1
fi

# 3. Run Cases
runCases
